#!/bin/bash
#-----------------------------------------------------------------------------
#   arcasHLA: high resolution HLA typing from RNA seq
#-----------------------------------------------------------------------------
#
#   Authors:    Rose Orenbuch, Ioan Filip, Itsik Pe'er
#   Date:       2019-06-26
#   Version:    0.2.0
#   License:    GNU
#
#-----------------------------------------------------------------------------
#   
#   arcasHLA types high resolution HLA alleles from BAM.
#
#-----------------------------------------------------------------------------
#   Dispatch
#-----------------------------------------------------------------------------
#
#   Argument parsing, tool dependency checks and subcommand dispatch are all
#   handled by scripts/arcasHLA.py, so this wrapper just forwards to it.
#-----------------------------------------------------------------------------

ARCASHLA_ROOT_DIR=$(realpath $(dirname $0))

python3 ${ARCASHLA_ROOT_DIR}/scripts/arcasHLA.py "$@"
#-------------------------------------------------------------------------------
